PREFIX cim: <http://www.symbiote-h2020.eu/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX spatial: <http://jena.apache.org/spatial#>

SELECT ?resource ?resourceName WHERE {
    ?sensor a cim:Resource.
	?sensor cim:name ?resourceName .
}