PREFIX cim: <http://www.symbiote-h2020.eu/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?sensor ?comment WHERE {
	?sensor a cim:Sensor ;
	        cim:description ?comment .
}