PREFIX cim: <http://www.symbiote-h2020.eu/ontology/core#>
PREFIX mim: <http://www.symbiote-h2020.eu/ontology/meta.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE { ?sensor ?p ?o } WHERE {
    ?senso
	?service mim:hasResource ?sensor .
	?sensor cim:id "102" .
}